### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by siv-swar** [muyu525/vmsg2csv#1]
The Conversion failed with the message as,

Traceback (most recent call last):
  File "vmsg2csv.py", line 203, in <module>

  File "vmsg2csv.py", line 70, in build_from_message
    else:
  File "vmsg2csv.py", line 145, in process_attribute
    # continue subject
  File "vmsg2csv.py", line 196, in process_continue_subject
    item = v[-1]
KeyError: 'content'

Also, the VMSG format seems to have changed. Please find below an example,

BEGIN:VMSG
VERSION: 1.1
BEGIN:VCARD
TEL:AX-ARWSLF
END:VCARD
BEGIN:VBODY
X-BOX:INBOX
X-READ:UNREAD
X-SIMID:0
X-LOCKED:UNLOCKED
X-TYPE:SMS
Date:2016/04/30 14:41:02
Subject;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:Dial and know your Airtel Mobile a/c details:=0D=0AOutstanding: _121_1#=
=0D=0AUnbilled: _121_2#=0D=0AData Topup: _121_10#=0D=0ABill Plan: _121_31#=
=0D=0AData Usage: _121_114#
END:VBODY
END:VMSG

Please help me at the earliest. Thanks

**Comment by muyu525** [comment]
Thanks for your comments, I fixed some errors.
May the output csv file is not what you want, but you can get raw data by modify this code.
At line 85, 'row' is a list which contains all data.

**Comment by muyu525** [comment]
Hi, siv-swar.
Thanks for your comments, I fixed some errors.
May the output csv file is not what you want, but you can get raw data by modify this code.
At line 85, 'row' is a list which contains all data.

**Comment by mattmill30** [comment]
I am also experiencing this issue.
I'm unable to understand your explanation.

I have attempted to use Python 2.7 and 3.7 with the following errors.
2.7:
Traceback (most recent call last):
  File "C:\Users\Matthew\Downloads\vmsg2csv-master\vmsg2csv.py", line 258, in <module>
    build_from_message(fvmsg, fcsv)
  File "C:\Users\Matthew\Downloads\vmsg2csv-master\vmsg2csv.py", line 78, in build_from_message
    process_attribute(line, stack, v_l)
  File "C:\Users\Matthew\Downloads\vmsg2csv-master\vmsg2csv.py", line 160, in process_attribute
    process_continue_subject(stream, v)
  File "C:\Users\Matthew\Downloads\vmsg2csv-master\vmsg2csv.py", line 220, in process_continue_subject
    item['content'] = item['content'] + content
KeyError: 'content'


3.7:
Traceback (most recent call last):
  File "C:\Users\Matthew\Downloads\vmsg2csv-master\vmsg2csv.py", line 257, in <module>

  File "C:\Users\Matthew\Downloads\vmsg2csv-master\vmsg2csv.py", line 77, in build_from_message
    else:
  File "C:\Users\Matthew\Downloads\vmsg2csv-master\vmsg2csv.py", line 159, in process_attribute
    # continue subject
  File "C:\Users\Matthew\Downloads\vmsg2csv-master\vmsg2csv.py", line 219, in process_continue_subject
    item = v[-1]
KeyError: 'content'


The format of the vmsg file I'm working with is:
BEGIN:VMSG
VERSION:1.1
BEGIN:VCARD
TEL:+447900000000
END:VCARD
BEGIN:VBODY
X-BOX:INBOX
X-MSGBOX:0
X-CALLTYPE:0
X-TYPEEX:0
X-KPAS_MSGID:0
X-KPAS_SERIAL_NUM:0
X-SPAM_REPORT:0
X-RESERVE_TIME:0
X-GROUP_ID:2145938456
X-INSERT_TIME:1569809001431
X-ORIGINAL_ADDR:0
X-EXTRA_DATA:
X-READ:UNREAD
X-SEEN:UNSEEN
X-SIMID:0
X-LOCKED:UNLOCKED
X-TYPE:SMS
Date:2019/09/30 00:00:00
Subject:H3llo W0rld!
line_address:
X-VERIFIED:0
END:VBODY
END:VMSG
